### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tdlogan**
# Overview
Adds additional detail to the Oculus Home games instruction. This clears up an additional step that should be taken to ensure Vive Dashboard is set up for SteamVR. 

# Changes
Only changes have been made to README.md

# Risk
Very low risk

### CODE REVIEW

**Comment by LibreVR** [comment]
That's strange, that really shouldn't be necessary. Did you disable it yourself at some point?

**Comment by LibreVR** [comment]
For now I've added the information to the troubleshooting wiki page: https://github.com/LibreVR/Revive/wiki/Troubleshooting#where-can-i-find-the-revive-dashboard

I think adding these steps to the ReadMe will just end up confusing more people than it helps.

**Comment by tdlogan** [comment]
Sounds good. I just followed the steps normally and then encountered the problem once I tried to boot up SteamVR. I didn't mess around with settings until I couldn't boot Vive Dashboard.

**Comment by LibreVR** [comment]
Very strange, maybe something changed. I'll try and confirm your findings or maybe I'll hear from other people encountering the same issue.

**Comment by tdlogan** [comment]
Sounds great

**Pull request closed without merging**
