### PR TITLE
Update multiplayer fix

### PR DESCRIPTION
**Pull request by ahmanwoods**
The Oculus API is now signed into on app launch with the titles appID, rather than on dashboard launch with the Oculus Platform appID

### CODE REVIEW

**Comment by CrossVR** [comment]
Hey man, this looks good, but needs a little bit of work to make the code style consistent. Will take it together with some OpenXR fixes for SteamVR soon and then roll a new release.

**Comment by ahmanwoods** [comment]
Sounds good. Thanks again!

**Comment by chaswa101** [comment]
Would this potentially fix the issue I am having with starting a game? The game loads up fine but then when searching for a game solo it just keeps spinning and spinning. For multiplayer searches it says that the service is unavailable.

**Comment by ahmanwoods** [comment]
It'd probably be best for you to open a separate github issue & I can try to help you there.

**Pull request merged**
