### PR TITLE
Multi libs

### PR DESCRIPTION
**Pull request by croger42**
So, these are my changes made on overlay and injector in order to manage more than one oculus app folder (app #928 enhancement)

Briefly: folders are retrieved from windows registry in ReviveManifestController and parsed in qml and js file, like before, but with an iteration.
For each app, a new parameter "baseLib" is added to revive manifest file and is used by main.cpp class of reviveInjector.

That's all.

### CODE REVIEW

**Comment by CrossVR** [comment]
I'll finish reviewing this on the weekend and merging it with my injector changes.

**Comment by CrossVR** [comment]
Looks good, injector needs some improvements but I'm rewriting that anyway.

**Comment by CrossVR** [comment]
Thanks again for this contribution, I've made a couple of changes that may be interesting for you:

The injector rewrite also introduced support for using the library GUID instead of specifying the base path: 87636be73257ba0ee5ad29e4129a70ef93ce2f37

The manifest verification code was slightly wrong, it would only attempt to remove the app when it was already removed from the manifest. I also optimized it so it would abandon the search early: 96b01004ab22a213786b2b16f653113d67cab17b

I moved the large qml object string to its own file and fixed libraries deleting each others tiles whenever they attempted to refresh: 7e37b748a6a8e49afa0537c6b4006bbe86639d9c

**Comment by croger42** [comment]
> Thanks again for this contribution, I've made a couple of changes that may be interesting for you:
> 
> The injector rewrite also introduced support for using the library GUID instead of specifying the base path: [87636be](https://github.com/LibreVR/Revive/commit/87636be73257ba0ee5ad29e4129a70ef93ce2f37)
> 
> The manifest verification code was slightly wrong, it would only attempt to remove the app when it was already removed from the manifest. I also optimized it so it would abandon the search early: [96b0100](https://github.com/LibreVR/Revive/commit/96b01004ab22a213786b2b16f653113d67cab17b)
> 
> I moved the large qml object string to its own file and fixed libraries deleting each others tiles whenever they attempted to refresh: [7e37b74](https://github.com/LibreVR/Revive/commit/7e37b748a6a8e49afa0537c6b4006bbe86639d9c)

Thank you for your message. I will checkout your changes on my fork. And yes, i changed manifest verification code several times and I have not tested it enough. It will be better next time !

**Pull request merged**
