### PR TITLE
Add hooking for Unity "ovr_Entitlement_GetIsViewerEntitled"

### PR DESCRIPTION
**Pull request by rjoudrey**
Here's my idea for hooking into the mono [DllImport] functions used in Unity apps. Seems to work as a hook, but my implementation of ovr_Entitlement_GetIsViewerEntitled() is either flawed or there are other methods that need to be hooked.

### CODE REVIEW

**Comment by LibreVR** [comment]
Why do you need to patch the Import Table? If it's importing the DLL at runtime, won't it call `GetProcAddress` anyway?

**Comment by rjoudrey** [comment]
From my understanding, the import address table for a module gets filled in with function addresses when it is loaded. Each module has a separate IAT and the function addresses are not inherited from the module that loaded it. I observed this by putting a log statement in HookGetProcAddress()

**Comment by LibreVR** [comment]
But unless it's statically linking the IAT is queried using `GetProcAddress`, so simply hooking that function should be enough. Anyway, we can always distill the workaround into it's necessary components after it works.

So be sure to let me know when you have something working, I don't have any other suggestions at this time. I'll be working on it again next week.

**Comment by rjoudrey** [comment]
The hook itself seems to work. Instead of getting an entitlement screen in Lucky's Tale, I see a black screen. If I comment out the ovr_Entitlement_GetIsViewerEntitled part, it instead shows the entitlement screen.

**Comment by LibreVR** [comment]
I'll test it tonight.

**Comment by LibreVR** [comment]
I can confirm that Lucky's Tale doesn't work yet, I will debug that game soon. Other Unity games seem fine however, so I will probably merge your code soon.

In any case, great work. I might be able to use your approach with IAT hooking for unreal games too so we don't need to copy DLLs to the main executable.

**Comment by LibreVR** [comment]
@rjoudrey As always, thank you for your contribution. Should I mention you in the next release or do you want to avoid drawing attention?

**Comment by rjoudrey** [comment]
Sure I don't mind

**Comment by LibreVR** [comment]
In commit 9cc744ca50abe6c66f55cff7bca40b29047dbbe6 I used the same IAT hooking method for Unreal games, works great no more spoofing platform DLLs.

**Comment by SRombauts** [comment]
Great! Any ETA for a release? 

Or would it be hard to build by myself (I am a C++ developer, but didn't find documentation on how-to build)

**Comment by LibreVR** [comment]
@SRombauts Sometime next week, I recommend just waiting until the next release when all games are supported again.

**Comment by SRombauts** [comment]
Understood, I will wait, thanks

**Comment by LibreVR** [comment]
@rjoudrey While very useful for Unreal Engine games, IAT hooking isn't required for Unity Engine games. API hooking works just fine there, but you have to enable the GetProcAddress hook, because it's only hooked until the Runtime is initialized.

**Comment by LibreVR** [comment]
@rjoudrey I found the problem with Lucky's Tale, they changed the startup scene to wait until the Health and Safety warning is dismissed. It seems I don't properly emulate that screen yet.

**Comment by rjoudrey** [comment]
@LibreVR that makes perfect sense... I remember observing that behavior but it didn't occur to me that the hook getting disabled was the issue. Glad you figured it out :+1:

**Comment by LibreVR** [comment]
@rjoudrey Fixed the bug with Lucky's Tale, going to put some finishing touches on it. Compatibility should be fully restored tomorrow.

**Pull request merged**
