### PR TITLE
Make LibRevive32 and LibRevive64 play nice together

### PR DESCRIPTION
**Pull request by rjoudrey**

### CODE REVIEW

**Comment by rjoudrey** [comment]
This doesn't work since openvr_api.dll is loaded relative to cwd.

**Comment by rjoudrey** [comment]
Working on fixing this.

**Comment by rjoudrey** [comment]
These two commits are ready for testing on your end.

**Comment by LibreVR** [comment]
@rjoudrey Actually, upon closer inspection, I see you also chose to inject `openvr_api.dll`. That's actually not needed, LibRevive will be able to find `openvr_api.dll` by itself if placed next to it.

**Comment by rjoudrey** [comment]
I had initially implemented it the way you suggested, but I found that the directory containing the LibRevive dll was not being searched. This is why I decided to inject it. The LoadLibrary documentation regarding DLL search paths seems to back up my observations as well. It says that DLLs are searched for in the directory containing the executable that created the process that is loading the DLL - which would be the directory containing ReviveInjector.exe (as well as PATH, etc.).

**Pull request merged**
