### PR TITLE
Trigger and Grip Button Swapped Mode

### PR DESCRIPTION
**Pull request by GiantSox**
In some games like Echo Arena, the grip button must be used very often, but the Toggle and Hybrid modes don't work well. I added a new grip mode ("revGrip_Trigger") that swaps the grip and trigger buttons. In Echo Arena the trigger isn't used nearly as often as the grip, so this makes the game much more comfortable to play.

### CODE REVIEW

**Comment by Armada651** [comment]
I think this should be done differently. There's lots of code duplication in the PR right now and it also doesn't allow you to use Toggle or Hybrid modes to toggle the trigger.

I'd suggest adding a boolean setting call `TriggerAsGrip` and if that setting is checked just swap out the two values like this:

```
if (TriggerAsGrip)
{
  float grip = inputState->HandTrigger[hand];
  inputState->HandTrigger[hand] = inputState->IndexTrigger[hand];
  inputState->IndexTrigger[hand] = grip;
}
```

That would do exactly what you're trying to do right now without duplicating code and still allowing the grip mode to be used to toggle the trigger.

**Comment by Armada651** [comment]
@GiantSox Could you make the changes if you agree with them?

**Comment by jordanManfrey** [comment]
...now that lone echo is out this should be high priority

**Comment by Armada651** [comment]
I'm going to release an update with input changes for Lone Echo / Echo Arena tomorrow. If you update your PR I can merge it, if not I'll probably just write the code myself.

**Pull request closed without merging**
